# Generated by Django 3.2.25 on 2024-06-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
